name: CI Pipeline for reuse workflows
# call workflows
on:
  workflow_dispatch: 
  push:
    branches:
      - main

  pull_request:
    branches:
      - main

permissions:  
  actions: read
  security-events: write
  packages: write
  contents: read
  

jobs:
  ci-pipeline-job:
    uses: VivekDandyan32/reusable-workflows/.github/workflows/ci-pipeline.yaml@main
    with:
      run_codeql: true
      run_sonarqube: true
      run_build: true
      run_publish-ghcr: true
    secrets: 
      SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
      DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
      DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
  
  depoy-with-kubectl:
    needs: ci-pipeline-job
    uses:  VivekDandyan32/reusable-workflows/.github/workflows/deployment-with-kubectl.yaml@main
    with:
      ENVIRONMENT: STAGING
      IMAGE_NAME: ghcr.io/vivekdandyan32/viki_app

    secrets:
      KUBECONFIG: ${{ secrets.KUBECONFIG }}  

  sel-tests:
    environment: STAGING      
    needs: depoy-with-kubectl
    runs-on: github-actions-scaleset-config-demo
    steps:
    - name: code checkout
      uses: actions/checkout@v5

    - name: setup python
      uses: actions/setup-python@v6
      with:
        python-version: '3.10'
    
    - name: Install Google Chrome
      run: |
        sudo apt-get update
        sudo apt-get install -y wget gnupg ca-certificates
        wget -q -O - https://dl.google.com/linux/linux_signing_key.pub | sudo apt-key add -
        echo "deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main" \
        | sudo tee /etc/apt/sources.list.d/google-chrome.list
        sudo apt-get update
        sudo apt-get install -y google-chrome-stable

    - name: Install dependencies
      run: |
        pip install -r requirements-tests.txt

    - name: Run Selenium Tests
      env: 
        APP_BASE_URL: ${{ vars.APP_BASE_URL }}
      run: |
        mkdir -p reports
        pytest tests/ --html=reports/selenium-report.html --self-contained-html

    - name: Upload Selenium Test Reports
      uses: actions/upload-artifact@v4
      with:
        name: selenium-test-report
        path: reports/

