name: helmcharts
# call workflows
on:
  workflow_dispatch: 

  pull_request:
    branches:
      - main

permissions:  
  actions: read
  security-events: write
  packages: write
  contents: read
  
env: 
  OCI_REGISTRY: ghcr.io
  OCI_REPOSITORY: ${{ github.repository_owner }}
jobs:
  # ci-pipeline-job:
  #   uses: VivekDandyan32/reusable-workflows/.github/workflows/ci-pipeline.yaml@main
  #   with:
  #     run_codeql: true
  #     run_sonarqube: true
  #     run_build: true
  #     run_publish-ghcr: true
  #   secrets: 
  #     SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
  #     DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
  #     DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
  
  # depoy-with-kubectl:
  #   needs: ci-pipeline-job
  #   uses:  VivekDandyan32/reusable-workflows/.github/workflows/deployment-with-kubectl.yaml@main
  #   with:
  #     ENVIRONMENT: STAGING
  #     IMAGE_NAME: ghcr.io/vivekdandyan32/viki_app

  #   secrets:
  #     KUBECONFIG: ${{ secrets.KUBECONFIG }}  

  # sel-tests:
  #   needs: depoy-with-kubectl
  #   uses: VivekDandyan32/reusable-workflows/.github/workflows/sel-run-tests.yaml@main
  #   with:
  #     ENVIRONMENT: STAGING
  publish-hc:
    runs-on: ubuntu-latest
    steps:
# install and configure helm 
      - name: checkout repo
        uses: actions/checkout@v5
      
      - name: setup helm
        uses: azure/setup-helm@v3
        with:
          version: v3.12.0
      
      - name: helm version
        run: helm version
  
# yq to update values in chart.yaml and values.yaml
      - name: Install yq
        run: |
          sudo curl -L https://github.com/mikefarah/yq/releases/latest/download/yq_linux_amd64 -o /usr/local/bin/yq
          sudo chmod +x /usr/local/bin/yq  

      - name: Check Helm & yq Version
        run: |
          helm version     
          yq --version

      - name: update image name in Chart 7 values YAML
        run: |
          export IMAGE_TAGS="${{ github.run_id}}-${GITHUB_SHA::7}"
          export VERSION="0.1.0-${IMAGE_TAGS}"
          yq e '.image.tag = strenv(IMAGE_TAGS)' charts/values.yaml -i
          yq e '.version = strenv(VERSION)' charts/Chart.yaml -i
          yq e '.appVersion = strenv(IMAGE_TAGS)' charts/Chart.yaml -i
          cat charts/values.yaml
          cat charts/Chart.yaml  
          
          
# lint helm files
      - name: helm lint
        run: helm lint charts/

# create helm chart via files in charts folder
      - name: create package
        run: |
          helm package charts/
          ls -ltr .

      - name: Check Helm & yq Version
        run: |
          helm version     
          yq --version
        
# push to cont registry  
      - name: Login to GHCR (OCI)
        run: |
          echo "${{ secrets.GITHUB_TOKEN }}" | helm registry login ${{ env.OCI_REGISTRY }} -u ${{ github.actor }} --password-stdin

      - name: Debug Push
        run: |
          export IMAGE_TAGS="${{ github.run_id }}-${GITHUB_SHA::7}"
          export VERSION="0.1.0-${IMAGE_TAGS}"

          echo "Registry : ${{ env.OCI_REGISTRY }}"
          echo "Repository : ${{ env.OCI_REPOSITORY }}"
          echo "Chart : viki-app-${VERSION}.tgz"
          echo "Target : oci://${{ env.OCI_REGISTRY }}/${{ env.OCI_REPOSITORY }}"
          
          
      - name: Push Helm Chart to GHCR (OCI)
        run: |
          export IMAGE_TAGS="${{ github.run_id}}-${GITHUB_SHA::7}"
          export VERSION="0.1.0-${IMAGE_TAGS}"
          helm push viki-app-${VERSION}.tgz oci://${{ env.OCI_REGISTRY }}/${{ env.OCI_REPOSITORY }}
      - name: Logout from GHCR
        run: helm registry logout ${{ env.OCI_REGISTRY }}



